import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import WebsiteHeader from "./components/shared/website-header";
import WebsiteFooter from "./components/shared/website-footer";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Giddaa Interview Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased font-figtree`}>
        <WebsiteHeader />
        <main className="pt-18.75">{children}</main>
        <WebsiteFooter />
      </body>
    </html>
  );
}
